# Generated by Django 4.2.5 on 2023-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('label', models.CharField(blank=True, default='', max_length=1000)),
                ('value', models.CharField(blank=True, default='', max_length=1000)),
                ('branches', models.ManyToManyField(related_name='branch', to='Qualifications_Managements.branches')),
                ('sem', models.ManyToManyField(related_name='sem', to='Qualifications_Managements.sems')),
                ('year', models.ManyToManyField(related_name='year', to='Qualifications_Managements.years')),
            ],
        ),
    ]
