# Generated by Django 4.2.5 on 2023-09-19 06:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_As_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(default=None, max_length=500)),
                ('password', models.CharField(default=None, max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('cell_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('f_name', models.CharField(default=None, max_length=100)),
                ('l_name', models.CharField(default=None, max_length=500)),
                ('user_type', models.CharField(default='company', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Register_As_Job_Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default=None, max_length=100)),
                ('l_name', models.CharField(default=None, max_length=500)),
                ('highest_qualification', models.CharField(default=None, max_length=500)),
                ('branch', models.CharField(default=None, max_length=500)),
                ('user_type', models.CharField(default='job_searcher', max_length=500)),
                ('username', models.CharField(default=None, max_length=500)),
                ('password', models.CharField(default=None, max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('cell_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('alternative_cell_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Register_As_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default=None, max_length=100)),
                ('l_name', models.CharField(default=None, max_length=500)),
                ('qualification', models.CharField(default=None, max_length=20)),
                ('year', models.CharField(blank=True, default=None, max_length=100)),
                ('sem', models.CharField(blank=True, default=None, max_length=100)),
                ('user_type', models.CharField(default='student', max_length=500)),
                ('username', models.CharField(default=None, max_length=500)),
                ('password', models.CharField(default=None, max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('cell_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('branch', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_Login_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=500)),
                ('url', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Reg_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=500)),
                ('url', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=500)),
                ('password', models.CharField(default=None, max_length=500)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('cell_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_type', models.CharField(default=None, max_length=500)),
                ('first_name', models.CharField(default=None, max_length=500)),
                ('last_name', models.CharField(default=None, max_length=500)),
                ('login_expire_time', models.DateTimeField(default=None)),
                ('login_token', models.CharField(default=None, max_length=1000)),
                ('user_status', models.CharField(blank=True, default=None, max_length=100)),
                ('last_login', models.DateTimeField(default=None, max_length=1000)),
            ],
        ),
    ]
