# Generated by Django 4.2.5 on 2023-09-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_as_job_searcher',
            name='alternative_cell_no',
        ),
    ]
