# Generated by Django 4.2.5 on 2023-09-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_System', '0002_remove_register_as_job_searcher_alternative_cell_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='login_expire_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='login_token',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
